const { test } = require('node:test');
const assert = require('node:assert/strict');
const A = require('../core.js');
const file = (name, size = 1, path = name) => ({ name, size, path });
test('does not start ready with no files', () => assert.equal(A.analyze('hello', []).ready, false));
test('attachment phrase without files blocks sending', () => assert.deepEqual(A.analyze('Please see attached.', []).blockers, ['mention-without-file']));
test('Chinese attachment phrase without files blocks sending', () => assert.equal(A.analyze('附件请查收', []).blockers[0], 'mention-without-file'));
test('selected files are ready if no contradiction', () => assert.equal(A.analyze('Hi', [file('report.pdf')]).ready, true));
test('detects named PDF absent from selection', () => assert.deepEqual(A.analyze('Attached: quote.pdf', [file('report.pdf')]).missingNamed, ['quote.pdf']));
test('detects a named file followed by an English full stop', () => assert.deepEqual(A.analyze('Please see invoice.pdf.', [file('README.md')]).missingNamed, ['invoice.pdf']));
test('detects paths in named references', () => assert.deepEqual(A.references('see docs/brief.docx'), ['docs/brief.docx']));
test('detects more than one named reference', () => assert.deepEqual(A.references('a.pdf and b.xlsx'), ['a.pdf', 'b.xlsx']));
test('does not mistake normal words for files', () => assert.deepEqual(A.references('please review the plan'), []));
test('named match is Unicode NFC and case insensitive', () => assert.equal(A.analyze('é.PDF', [file('é.pdf')]).missingNamed.length, 0));
test('zero-byte file blocks sending', () => assert.ok(A.analyze('Attached.', [file('a.txt', 0)]).blockers.includes('zero-byte')));
test('directional name blocks sending', () => assert.ok(A.analyze('Attached.', [file('a\u202eb.pdf')]).blockers.includes('unsafe-name')));
test('duplicate names advisory does not block', () => { const r=A.analyze('Attached.', [file('a.pdf'),file('A.pdf')]); assert.equal(r.ready,true); assert.equal(r.duplicates.length,1); });
test('files without wording are an advisory', () => assert.ok(A.analyze('Hello', [file('a.pdf')]).advisories.includes('files-without-message-mention')));
test('compose retains message and adds list', () => assert.match(A.compose('Hello', [file('a.pdf', 1536)]), /Hello\n\nAttachments \(1\)\n1\. a\.pdf \(1\.5 KB\)/));
test('compose Chinese uses Chinese heading', () => assert.match(A.compose('', [file('a.pdf')], 'zh'), /附件（1 个）/));
test('compose does not invent an empty attachment list', () => assert.equal(A.compose('Please see attached.', []), 'Please see attached.'));
test('sizes are human readable', () => { assert.equal(A.size(0),'0 B'); assert.equal(A.size(1024),'1.0 KB'); assert.equal(A.size(10485760),'10 MB'); });
test('report states boundary', () => assert.match(A.report(A.analyze('Attached.', [file('a.pdf')])), /cannot confirm contents/));
test('report shows missing names in Chinese', () => assert.match(A.report(A.analyze('x.pdf', []),'zh'), /文中点名但未选中/));
test('file count limit is explicit', () => assert.throws(() => A.analyze('', Array(10001).fill(file('a')))));
test('message limit is explicit', () => assert.throws(() => A.analyze('a'.repeat(1000001), [])));
test('bad metadata rejects rather than guessing', () => assert.throws(()=>A.analyze('', [{name:'x',size:-1}])));
test('input files are not mutated', () => { const f=[file('x.pdf')]; const before=JSON.stringify(f); A.analyze('x.pdf',f); assert.equal(JSON.stringify(f),before); });
