(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const state = { files: [], language: localStorage.getItem('attachsure-language') || 'en', demo: false, result: null };
  const strings = {
    en: { language:'中文',eyebrow:'A small pre-send check',title:'Your words say “attached.”<br>Your files should agree.',lede:'A private, offline check for email, WeChat, and web-chat copy. No upload, no account, no sending.',privacy:'Works in this browser. File contents are never read.',messageLabel:'Paste the message you plan to send',messagePlaceholder:'Hi Maya — please see the attached Q3 report and invoice.pdf. Thank you.',messageHint:'We only examine the text locally.',fileLabel:'Choose the files you will attach',dropTitle:'Choose files or drop them here',dropHint:'Names and sizes only — their contents stay untouched.',noFiles:'No files selected',clear:'Clear',demo:'Try an example',check:'Check before sending',resultEyebrow:'Result',copyLabel:'Copy-ready attachment note',copyHint:'This app never sends it for you.',copy:'Copy text',download:'Download check',boundary:'A green result checks wording and file metadata only. You still need to verify contents, recipient, attachment/upload, and delivery.',howEyebrow:'A calm last look',howOneTitle:'Spot contradictions',howOneText:'“See invoice.pdf” with no invoice selected? We flag it before the window closes.',howTwoTitle:'Make attachments legible',howTwoText:'Generate a clean, size-aware list for the person on the other end.',howThreeTitle:'Keep control',howThreeText:'Copy the text, then attach and send in the app you already use.',footer:'A tiny local companion for the send button.',readyTitle:'Looks consistent',readySummary:'No wording/file contradiction was found. Make the final manual checks before you send.',needsTitle:'Pause for a quick check',needsSummary:'We found something worth resolving before you copy or send.',issueNoFiles:'Your message mentions an attachment, but no file is selected.',issueNamed:'Your message names file(s) that are not selected.',issueZero:'A selected file is 0 B — it may be empty.',issueUnsafe:'A filename contains an invisible control or direction character.',issueNoMention:'Files are selected, but your message does not mention attachments.',issueDuplicate:'Multiple selected files share the same name. Confirm you mean to send each one.',copied:'Copied',copyFail:'Select and copy manually',downloadName:'attachsure-check.json',fileCount:n=>`${n} file${n===1?'':'s'} selected` },
    zh: { language:'English',eyebrow:'一个小小的发送前检查',title:'正文写着“附件已附”。<br>文件也该一致。',lede:'面向邮件、微信和网页聊天的离线校验：不上传、不登录、不代发。',privacy:'只在当前浏览器运行，不读取文件内容。',messageLabel:'粘贴准备发送的正文',messagePlaceholder:'Maya 你好，附件是 Q3 报告和 invoice.pdf，请查收。谢谢！',messageHint:'只在本地检查文字。',fileLabel:'选择准备添加的文件',dropTitle:'选择文件，或拖到这里',dropHint:'只读取名称和大小，文件内容不会被触碰。',noFiles:'尚未选择文件',clear:'清空',demo:'试用示例',check:'发送前检查',resultEyebrow:'检查结果',copyLabel:'可直接复制的附件说明',copyHint:'本工具不会替你发送。',copy:'复制文本',download:'下载检查结果',boundary:'绿色结果只代表正文与文件元数据没有发现矛盾；仍需人工确认内容、收件人、附件/上传和送达。',howEyebrow:'给发送键前的一眼',howOneTitle:'发现矛盾',howOneText:'正文写“见 invoice.pdf”，但没选中它？窗口关闭前就能发现。',howTwoTitle:'说清附件',howTwoText:'生成清爽、带大小的附件列表，方便对方核对。',howThreeTitle:'保持掌控',howThreeText:'复制文本，再到你平时使用的应用里添加附件并发送。',footer:'发送键旁的一个本地小助手。',readyTitle:'看起来一致',readySummary:'未发现正文和文件的矛盾。发送前仍请完成最后的人工核对。',needsTitle:'先停一下，快速确认',needsSummary:'发现了值得在复制或发送前处理的事项。',issueNoFiles:'正文提到了附件，但尚未选中任何文件。',issueNamed:'正文点名的文件没有被选中。',issueZero:'选中的文件为 0 B，可能是空文件。',issueUnsafe:'文件名包含不可见控制字符或方向字符。',issueNoMention:'已选文件，但正文没有提到附件。',issueDuplicate:'多个选中文件同名。请确认确实都要发送。',copied:'已复制',copyFail:'请手动全选复制',downloadName:'attachsure-检查结果.json',fileCount:n=>`已选 ${n} 个文件` }
  };
  function t(key, ...args) { const value = strings[state.language][key]; return typeof value === 'function' ? value(...args) : value; }
  function renderLanguage() { document.documentElement.lang = state.language === 'zh' ? 'zh-CN' : 'en'; document.title = state.language === 'zh' ? 'AttachSure — 发送前检查' : 'AttachSure — before you send'; document.querySelectorAll('[data-i18n]').forEach(el => el.innerHTML = t(el.dataset.i18n)); document.querySelectorAll('[data-i18n-placeholder]').forEach(el => el.placeholder = t(el.dataset.i18nPlaceholder)); $('language').textContent=t('language'); renderFiles(); if(state.result) renderResults(state.result); }
  function accepted(files) { return Array.from(files).slice(0, AttachSure.MAX_FILES).map(file => ({name:file.name,size:file.size,path:file.webkitRelativePath||file.name})); }
  function renderFiles() { $('file-summary').textContent = state.files.length ? t('fileCount', state.files.length) : t('noFiles'); $('clear-files').hidden=!state.files.length; $('file-list').innerHTML=state.files.map(f=>`<li class="file-item"><span>${escapeHtml(f.path)}</span><span>${AttachSure.size(f.size,state.language)}</span></li>`).join(''); }
  function escapeHtml(text) { const el=document.createElement('span'); el.textContent=text; return el.innerHTML; }
  function setFiles(files) { state.files=accepted(files); state.demo=false; $('files').value=''; renderFiles(); }
  function issue(title, text, advisory=false) { return `<div class="issue${advisory?' advisory':''}"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(text)}</p></div>`; }
  function renderResults(result) { const hasIssues=result.blockers.length||result.advisories.length; $('results').hidden=false; $('verdict').textContent=result.ready?t('readyTitle'):t('needsTitle'); $('result-summary').textContent=result.ready?t('readySummary'):t('needsSummary'); $('status-dot').className=`status-dot ${result.ready?'ready':'warn'}`; const issues=[];
    if(result.blockers.includes('mention-without-file')) issues.push(issue(t('issueNoFiles'),''));
    if(result.blockers.includes('named-file-not-selected')) issues.push(issue(t('issueNamed'),result.missingNamed.join(' · ')));
    if(result.blockers.includes('zero-byte')) issues.push(issue(t('issueZero'),result.zeroByte.map(f=>f.name).join(' · ')));
    if(result.blockers.includes('unsafe-name')) issues.push(issue(t('issueUnsafe'),result.suspicious.map(f=>f.name).join(' · ')));
    if(result.advisories.includes('files-without-message-mention')) issues.push(issue(t('issueNoMention'),' ',true));
    if(result.advisories.includes('duplicate-name')) issues.push(issue(t('issueDuplicate'),result.duplicates.map(g=>g.map(f=>f.name).join(' / ')).join(' · '),true));
    $('issues').innerHTML=issues.join(''); $('composed').value=AttachSure.compose($('message').value,state.files,state.language); if(!hasIssues && !result.ready) $('issues').innerHTML='';
  }
  function check() { state.result=AttachSure.analyze($('message').value,state.files); renderResults(state.result); $('results').scrollIntoView({behavior:'smooth',block:'nearest'}); }
  $('message').addEventListener('input',()=>{ $('char-count').textContent=`${$('message').value.length.toLocaleString()} / 1,000,000`; state.demo=false; });
  $('files').addEventListener('change',event=>setFiles(event.target.files));
  $('clear-files').addEventListener('click',()=>setFiles([]));
  ['dragenter','dragover'].forEach(type=>$('drop-zone').addEventListener(type,event=>{event.preventDefault();$('drop-zone').classList.add('drag');}));
  ['dragleave','drop'].forEach(type=>$('drop-zone').addEventListener(type,event=>{event.preventDefault();$('drop-zone').classList.remove('drag');}));
  $('drop-zone').addEventListener('drop',event=>setFiles(event.dataTransfer.files));
  $('check').addEventListener('click',check);
  $('demo').addEventListener('click',()=>{ state.files=[{name:'Q3-report.pdf',size:2480128,path:'Q3-report.pdf'},{name:'invoice.pdf',size:84432,path:'invoice.pdf'}]; $('message').value=state.language==='zh'?'Maya 你好，附件是 Q3 报告和 invoice.pdf，请查收。':'Hi Maya — attached are the Q3 report and invoice.pdf. Thank you.'; $('char-count').textContent=`${$('message').value.length.toLocaleString()} / 1,000,000`; state.demo=true; renderFiles(); check(); });
  $('language').addEventListener('click',()=>{state.language=state.language==='en'?'zh':'en';localStorage.setItem('attachsure-language',state.language);renderLanguage();});
  $('copy').addEventListener('click',async()=>{ const button=$('copy'); try { await navigator.clipboard.writeText($('composed').value); button.textContent=t('copied'); setTimeout(()=>button.textContent=t('copy'),1500); } catch { $('composed').focus(); $('composed').select(); button.textContent=t('copyFail'); } });
  $('download').addEventListener('click',()=>{ if(!state.result) return; const payload={...state.result, generatedAt:new Date().toISOString(), demo:state.demo, report:AttachSure.report(state.result,state.language)}; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})); a.download=t('downloadName'); a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),0); });
  renderLanguage();
})();
